kafka cannot support nonroutable meta-address 0.0.0.0
streamnative/kop pull request #1039
Opened 2022-01-27 07:34 UTC by wenbingshen

Fixes #1038 

`kafkaListeners` and `kafkaAdvertisedListeners` will expose metadata addresses to kafka clients, if configured as `0.0.0.0 ` address that cannot be routed, clients will not be able to access the service address.

2022-01-29 03:07 UTC, BewareMyPower requested changes
I think this fix is not reasonable. `kafkaListeners` is a set of listeners that KoP binds to. They should not be exposed to Kafka client.

2022-01-29 04:50 UTC, wenbingshen commented
@BewareMyPower I haven't taken a closer look at the implementation logic of kOP in this area yet, I'm currently on the high speed train, I'll take a look in a few days. Thanks.

2022-01-29 06:04 UTC, BewareMyPower commented
You can see https://github.com/streamnative/kop/blob/master/docs/configuration.md#listeners for the difference between `kafkaListeners` and `kafkaAdvertisedListeners`. You can see more details in [KIP 103](https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic).

2022-01-30 11:02 UTC, wenbingshen commented
> You can see https://github.com/streamnative/kop/blob/master/docs/configuration.md#listeners for the difference between `kafkaListeners` and `kafkaAdvertisedListeners`. You can see more details in [KIP 103](https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic).

Happy Chinese New Year. I'll turn off the PR for now, and I'll look into this in more detail in KIP 103 when I have time. Thanks.

2022-01-30 11:02 UTC, closed without merging