[security] Upgrade jackson-databind to get rid of CVE-2020-36518
streamnative/kop pull request #1213
Opened 2022-03-28 12:56 UTC by nicoloboschi

See the related pull in Pulsar https://github.com/apache/pulsar/pull/14871

2022-03-28 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/kop?pullRequest=1213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/kop?pullRequest=1213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/kop?pullRequest=1213) it.</sub>

2022-03-29 04:43 UTC, BewareMyPower requested changes

2022-03-29 04:43 UTC, BewareMyPower commented on pom.xml
> +    <jackson-databind.version>2.12.6.1</jackson-databind.version>
```suggestion
    <jackson.version>2.13.2</jackson.version>
    <jackson-databind.version>2.13.2.1</jackson-databind.version>
```

I think we need to upgrade the version to 2.13.2 or higher, see https://nvd.nist.gov/vuln/detail/CVE-2020-36518 and https://github.com/apache/pulsar/pull/14871.

2022-03-29 07:34 UTC, nicoloboschi commented on pom.xml
> +    <jackson-databind.version>2.12.6.1</jackson-databind.version>
@BewareMyPower 2.12.6.1 also contains the fix, see [here](https://github.com/FasterXML/jackson-databind/issues/2816#issuecomment-1081046753)

I thought it was better to not upgrade to 2.13.x as it is a more conservative choice. Let me know if you think it's worth to upgrade to 2.13

2022-03-29 08:24 UTC, BewareMyPower commented on pom.xml
> +    <jackson-databind.version>2.12.6.1</jackson-databind.version>
IMO, it's better to keep it consistent with Pulsar's dependency.

2022-03-29 08:43 UTC, BewareMyPower approved these changes

2022-03-29 09:10 UTC, merged