Add migration handler
streamnative/kop pull request #1476
Opened 2022-09-12 11:46 UTC by ZiyaoWei

Master Issue: #1475

### Motivation

The migration service needs a set of API for the clients to talk to.

### Modifications

This adds the HTTP request handling boilerplate for the new live migration service. Note this is largely based on the Schema Registry HTTP handling code and listens to a separate port from the main Kafka listener, and in the future we should probably refactor the Schema Registry code to using this common boilerplate.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

The migration service is WIP so no tests are written yet but we can make sure the endpoint works by visiting it.

### Documentation
  
- [ ] `no-need-doc` 
  
  Doesn't need docs at this moment, will add doc after the live migration service is done.

2022-09-12 11:48 UTC, eolivelli commented
Can you please share your plan ?
do you have some design document ?

2022-09-12 17:02 UTC, lin-zhao requested changes
Mostly styling questions. But Unit tests are missing in this PR. They should be added before merge.

2022-09-12 17:02 UTC, lin-zhao commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessor.java
> +            httpResponse = new DefaultFullHttpResponse(HTTP_1_1, error,
This is a duplicate of line 82. There should be a better way to organize this.

If there's no equivalent of `Try` class of scala, how about

```
String body = "Error " + err;
try {
    body = MAPPER.writeValueAsString(new ErrorModel(httpStatusCode, err.getMessage()));
} catch (JsonProcessingException impossible) {
} finally {
  httpResponse = ...
}
```

2022-09-27 04:48 UTC, lin-zhao approved these changes
LGTM

2022-09-28 02:13 UTC, BewareMyPower approved these changes

2022-09-28 02:14 UTC, merged