[FEATURE #1547] Support broker level entry filter for consumer
streamnative/kop pull request #1548
Opened 2022-10-27 02:25 UTC by lwclover

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2022-10-27 02:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/kop?pullRequest=1548) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/kop?pullRequest=1548) before we can accept your contribution.<br/><hr/>**sunhangda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/kop?pullRequest=1548) it.</sub>

2022-10-27 03:34 UTC, BewareMyPower requested changes
Could you add a test to test a customized entry filter?

2022-10-27 08:56 UTC, lwclover commented
> Could you add a test to test a customized entry filter?

OK

2022-10-28 02:08 UTC, lwclover commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/AbstractEntryFormatter.java
> +                                                                    List<EntryFilterWithClassLoader> entryFilters) {
done

2022-10-28 02:41 UTC, BewareMyPower submitted a review, later dismissed

2022-10-28 04:52 UTC, Demogorgon314 reviewed
```java
EntryFormatterFactory.create(kafkaConfig, pulsarService.getBrokerService().getEntryFilters());
```
Can we pass the entry filter through the EntryFormatter constructors?

2022-10-28 05:35 UTC, lwclover commented
> Can we pass the entry filter through the EntryFormaatter constructors?

Good idea

2022-10-28 07:48 UTC, BewareMyPower approved these changes

2022-10-28 07:50 UTC, Demogorgon314 approved these changes

2022-10-31 03:22 UTC, merged