Fix list offsets for times failure when ledgers are removed by a roll…
streamnative/kop pull request #1847
Opened 2023-05-12 09:29 UTC by zhouxy0809

…over operation

### Motivation
When lac ledger is expired or removed，KafkaRequestHandler.fetchOffsetByTimestamp call failed and `NonRecoverableLedgerException` will be thrown.
- When lac ledger is expired or removed，the first legerId in managedLedger is greater than the lac ledgerId , then the `asyncFindNewestMatching.startPosition` is lac'sLedgerId:0. 
- `OpFindNewestEntry.find` will read `startPosition`'s entry, then managedLedger will thrown `NonRecoverableLedgerException`

### Modifications

- Handle the NonRecoverableLedgerException in findEntryFailed callback. In this case, return the LEO as the offset because we can treat the topic as empty.

2023-05-16 12:26 UTC, BewareMyPower requested changes
Could you change the target branch to `master` so that we can cherry-pick it to all release branches?

2023-05-18 02:11 UTC, zhouxy0809 commented
> Could you change the target branch to `master` so that we can cherry-pick it to all release branches?

I have changed target branch to `master`，and should I change source branch to `master`?

2023-05-18 02:42 UTC, Demogorgon314 commented
Can you push a new PR base on the master branch? Look like you are using branch-2.9.4 to push the PR.

2023-05-18 02:47 UTC, zhouxy0809 commented
> Can you push a new PR base on the master branch? Look like you are using branch-2.9.4 to push the PR.

Thanks for your advice

2023-05-18 03:08 UTC, closed without merging