Fix unknown exception caused by thread safety issue
streamnative/kop pull request #2033
Opened 2023-12-28 12:12 UTC by 315157973

### Motivation
Both the response thread and timeout detection thread will access PendingProduceCallback
This problem will easily occur when the sending latency is close to the timeout threshold.

Step-1： response thread and timeout detection thread access 1 at the same time, none of them meet the conditions for return

Step-2: timeout detection thread execute to 2, and set responseMap = null
Setp-3: response thread execute to 3,  cause NPE

<img width="864" alt="image" src="https://github.com/streamnative/kop/assets/9758905/96a1a8f5-cf09-4bcd-8f4a-24f9c8205474">

### Modifications
Add synchronized

### Documentation

- [x] `no-need-doc`

2023-12-28 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/kop?pullRequest=2033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/kop?pullRequest=2033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/kop?pullRequest=2033) it.</sub>

2023-12-29 03:18 UTC, BewareMyPower commented
Could you sign the CLA?

2023-12-29 03:34 UTC, BewareMyPower approved these changes

2023-12-29 06:24 UTC, Demogorgon314 approved these changes

2023-12-29 11:49 UTC, BewareMyPower requested changes
The spotbugs check failed:

```
Medium: Inconsistent synchronization of io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback.responseMap; locked 60% of time [io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback, io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback, io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback, io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback, io.streamnative.pulsar.handlers.kop.storage.ReplicaManager$PendingProduceCallback] Unsynchronized access at ReplicaManager.java:[line 119]Unsynchronized access at ReplicaManager.java:[line 121]Synchronized access at ReplicaManager.java:[line 127]Synchronized access at ReplicaManager.java:[line 125]Synchronized access at ReplicaManager.java:[line 133] IS2_INCONSISTENT_SYNC
```

You need to check the synchronized code blocks again.

BTW, in our private fork, this pending produce is removed and the `timeout` field is not processed.

2023-12-31 08:51 UTC, BewareMyPower approved these changes

2024-01-04 01:18 UTC, merged