remove unnecessary topics cache for Topic Manager
streamnative/kop pull request #267
Opened 2020-12-16 09:29 UTC by dockerzhang

fixs #226

2020-12-17 02:07 UTC, BewareMyPower commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
> -                removeTopicManagerCache(topicName);
Should `removeTopicManagerCache` be retained?

2020-12-17 12:39 UTC, jiazhai commented
@dockerzhang Thanks for the change. Would you please help add the dedicated test cases to test the new code path? 
So the code could be protected by the test cases.

2020-12-18 01:59 UTC, dockerzhang commented
@jiazhai there is existed `KafkaTopicManager` UT for this PR.
@BewareMyPower the newest topic cache only serve to remove the producer after the connection close.

2020-12-18 02:42 UTC, BewareMyPower requested changes

2020-12-18 02:42 UTC, BewareMyPower commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
>                      topicFuture.get().removeProducer(references.get(topicName));
`topicFuture.get()` needs a null check because the topic future that was put to `topics` may complete with null.

2020-12-18 03:03 UTC, BewareMyPower approved these changes

2020-12-18 03:04 UTC, BewareMyPower commented
LGTM. PTAL again @jiazhai

2020-12-28 10:57 UTC, merged