add prometheus metric exporter framework
streamnative/kop pull request #389
Opened 2021-03-01 16:17 UTC by hangc0276

### Motivation
KOP doesn't expose prometheus metrics to monitor running stats, which will be hard the debug performance problem.

### Changs
1. add Prometheus metrics provider for kop and use individual port to expose kop metrics
2. Due to BookKeeper Prometheus metric provider include basic metrics stats, such as jvm metrics, memory metrics, cpu metric etc, which will lead those metrics register twice. When run kop with pulsar broker, the prometheus metric thread will start failed.

2021-03-02 12:55 UTC, codelipenghui reviewed
@hangc0276 We can expose metrics through /metrics endpoint of the broker directly, I have add Raw Metrics Provider in Pulsar (https://github.com/apache/pulsar/pull/9021), you can use it to expose additional metrics to the broker metrics endpoint.

2021-03-02 14:13 UTC, BewareMyPower commented
The `kafka-impl/conf` won't be used anymore (see #387 ), please edit `docs/configuration.md` or add a new document for exposing metrics to Prometheus under `docs` directory and add a link in `README.md`.

2021-03-28 04:53 UTC, hangc0276 commented
> @hangc0276 We can expose metrics through /metrics endpoint of the broker directly, I have add Raw Metrics Provider in Pulsar ([apache/pulsar#9021](https://github.com/apache/pulsar/pull/9021)), you can use it to expose additional metrics to the broker metrics endpoint.

@codelipenghui Ok, I update the code and use pulsar raw metrics provider to expose kop metrics to pulsar metrics group. Please take a look. Thanks.

2021-03-28 05:25 UTC, BewareMyPower commented
You should fix the code style first. Then please remove `kafka-impl/conf/broker.conf`. It's unused.

Regarding how to enable the monitor for prometheus, we can open a new PR to add the docs.

2021-03-28 23:19 UTC, jiazhai approved these changes

2021-03-28 23:24 UTC, jiazhai commented
opened a new issue for the doc. @codelipenghui @BewareMyPower Would you please help review it again?

2021-03-29 01:40 UTC, BewareMyPower requested changes

2021-03-29 01:40 UTC, BewareMyPower commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
> +
```suggestion
```

2021-03-29 01:40 UTC, BewareMyPower commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
> +
Remove unused variable

2021-03-29 01:43 UTC, BewareMyPower requested changes

2021-03-29 01:43 UTC, BewareMyPower commented on tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
> +        Assert.assertTrue(sb.toString().contains("kop_server_HANDLE_PRODUCE_REQUEST"));
Could you add checks for all the metrics you added? Like `kop_server_PRODUCE_ENCODE` and others.

2021-03-29 02:36 UTC, BewareMyPower commented
I've left a few comments, PTAL.

2021-03-29 03:26 UTC, hangc0276 commented
> I've left a few comments, PTAL.

@BewareMyPower  OK， i will fix it

2021-04-01 02:41 UTC, BewareMyPower approved these changes

2021-04-01 02:41 UTC, merged