[ENHANCEMENT] perf tuning in decode phrase
streamnative/kop pull request #394
Opened 2021-03-08 07:27 UTC by wuzhanpeng

### Motivation
The decode method in `KafkaEntryFormatter` is time-consuming among which the process of constructing `MemoryRecordsBuilder` takes the highest proportion of time. 

### Designing
Therefore our aims are:
1. overwrites `BaseOffset` field in byte buffer directly to avoid time-consuming iteration which is mainly used for assigning offsets
2. concatenates multiple record batches into one `MemoryRecords` object to better simulate kafka's behavior

### Modifications
- remove the iteration of continuously appending records in the `MemoryRecordsBuilder`
- change to one-to-one correspondence between batch and entry

2021-03-08 10:11 UTC, BewareMyPower requested changes

2021-03-08 10:11 UTC, BewareMyPower commented on kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
> +
Please change the imports order to make `check-style` plugin succeed.

2021-03-08 10:19 UTC, jiazhai approved these changes

2021-03-09 12:41 UTC, BewareMyPower approved these changes

2021-03-09 12:56 UTC, merged