create kafka namespace if missing
streamnative/kop pull request #593
Opened 2021-06-25 03:16 UTC by aloyszhang

Currently when KoP  only creates the namespace for kafka metadata defined by `kafkaMetadataTenant` and `kafkaMetadataNamespace` when started, but not create the namespaces for kafka topics defined by `kafkaTenant` and `kafkaNamespace`.

This pull requeset add the initialization of namespaces for kafka topic.

2021-06-25 09:07 UTC, aloyszhang commented
@BewareMyPower @hangc0276 PTAL

2021-06-28 01:45 UTC, BewareMyPower requested changes

2021-06-28 01:45 UTC, BewareMyPower commented on tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java
> +        }
Could you just remove these code? Then it can also verify your change works.

2021-06-28 06:10 UTC, BewareMyPower approved these changes

2021-06-28 06:11 UTC, merged